# Copyright 2010 - 2012, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
clientDistDir = '$DISTDIR/samples/secure'
env1 = env.Clone();
env2 = env.Clone();
env1.Append(CPPDEFINES=[('CLIENT=1')])
env2.Append(CPPDEFINES=[('CLIENT=2')])

obj = env2.Object('DeskTopSharedKSClient2',  ['DeskTopSharedKSClient.cc'])

# Sample Programs
progs = [
    env1.Program('DeskTopSharedKSClient1',  ['DeskTopSharedKSClient.cc']),
    env2.Program('DeskTopSharedKSClient2',  [obj]),
    env.Program('DeskTopSharedKSService', ['DeskTopSharedKSService.cc'])
    ]

#if 'linux' == env['OS'] or 'darwin' == env['OS']:
#    env.Install('$DISTDIR/bin/samples', progs )
#    env.Install(clientDistDir, env.Glob('*.cc'))
#    env.Install(clientDistDir, env.Glob('Make*'))
#    env.Install(clientDistDir, env.Glob('README*'))
#elif env['OS_GROUP'] == 'windows':
#    env.Install('$DISTDIR/bin/samples', progs )
#    env.Install(clientDistDir, env.Glob('*.cc'))
