# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = []

# Install sample source
clientDistDir = '$DISTDIR/samples/chat'
if env['OS'] == 'android':
    returnValue += env.Install(clientDistDir, 'android/AndroidManifest.xml')
    returnValue += env.Install(clientDistDir, 'android/.classpath')
    returnValue += env.Install(clientDistDir, 'android/.project')
    returnValue += env.Install(clientDistDir, 'android/default.properties')
    returnValue += env.Install(clientDistDir, Dir('android/jni').srcnode())
    returnValue += env.Install(clientDistDir, Dir('android/src').srcnode())
    returnValue += env.Install(clientDistDir, Dir('android/res').srcnode())
elif env['OS'] == 'linux' or 'darwin' == env['OS']:
    env.Program('chat', ['linux/chat.cc'])
    returnValue += env.Install('$DISTDIR/bin/samples', ['chat'])
    returnValue += env.Install(clientDistDir, env.Glob('linux/*.cc'))
    returnValue += env.Install(clientDistDir, env.Glob('linux/Make*'))
elif env['OS_GROUP'] == 'windows':
    env.Program('chat', ['linux/chat.cc'])
    returnValue += env.Install('$DISTDIR/bin/samples', ['chat.exe'])
    returnValue += env.Install(clientDistDir, env.Glob('linux/*.cc'))
    #install Visual Studio solution files
    returnValue += env.Install(clientDistDir+'/VC2008Win7', 'linux/VC2008Win7/VC2008Win7.sln')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/chatsample', 'linux/VC2008Win7/chatsample/chatsample.vcproj')

Return ('returnValue')
