# Copyright 2012, 2013 Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
clientDistDir = '$CPP_DISTDIR/samples/FileTransfer'

# The return value is the collection of files installed in the build destination.
returnValue = []

# Sample Programs
progs = [
    env.Program('FileTransferClient',  ['FileTransferClient.cc']),
    env.Program('FileTransferService', ['FileTransferService.cc'])
    ]
if 'linux' == env['OS'] or 'darwin' == env['OS']:
    returnValue += env.Install('$CPP_DISTDIR/bin/samples', progs )
    returnValue += env.Install(clientDistDir, env.Glob('*.cc'))
elif env['OS_GROUP'] == 'windows':
    returnValue += env.Install('$CPP_DISTDIR/bin/samples', progs )
    returnValue += env.Install(clientDistDir, env.Glob('*.cc'))
    returnValue += env.InstallAs(clientDistDir + '/README.txt', 'README.windows.txt')
    #install Visual Studio solution files
    returnValue += env.Install(clientDistDir+'/VC2008Win7', 'VC2008Win7/VC2008Win7.sln')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/FileTransferClient', 'VC2008Win7/FileTransferClient/FileTransferClient.vcproj')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/FileTransferService', 'VC2008Win7/FileTransferService/FileTransferService.vcproj')

Return ('returnValue')
