# Copyright 2012, 2013 Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
clientDistDir = '$DISTDIR/samples/FileTransfer'

# The return value is the collection of files installed in the build destination.
returnValue = []

# Sample Programs
progs = [
    env.Program('FileTransferClient',  ['FileTransferClient.cc']),
    env.Program('FileTransferService', ['FileTransferService.cc'])
    ]
if 'linux' == env['OS'] or 'darwin' == env['OS'] or env['OS_GROUP'] == 'windows':
    returnValue += env.Install('$DISTDIR/bin/samples', progs )
    returnValue += env.Install(clientDistDir, env.Glob('*.cc'))

Return ('returnValue')
