# Copyright 2010 - 2011, 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = []

# Install sample source
if env['OS'] == 'android':
    clientDistDir = '$DISTDIR/samples/simple/client'
    returnValue += env.Install(clientDistDir, env.Glob('android/client/AndroidManifest.xml'))
    returnValue += env.Install(clientDistDir, env.Glob('android/client/.classpath'))
    returnValue += env.Install(clientDistDir, env.Glob('android/client/.project'))
    returnValue += env.Install(clientDistDir, env.Glob('android/client/default.properties'))
    returnValue += env.Install(clientDistDir, Dir('android/client/.settings').srcnode())
    returnValue += env.Install(clientDistDir, Dir('android/client/jni').srcnode())
    returnValue += env.Install(clientDistDir, Dir('android/client/src').srcnode())
    returnValue += env.Install(clientDistDir, Dir('android/client/res').srcnode())

    serviceDistDir = '$DISTDIR/samples/simple/service'
    returnValue += env.Install(serviceDistDir, env.Glob('android/service/AndroidManifest.xml'))
    returnValue += env.Install(serviceDistDir, env.Glob('android/service/.classpath'))
    returnValue += env.Install(serviceDistDir, env.Glob('android/service/.project'))
    returnValue += env.Install(serviceDistDir, env.Glob('android/service/default.properties'))
    returnValue += env.Install(serviceDistDir, Dir('android/service/.settings').srcnode())
    returnValue += env.Install(serviceDistDir, Dir('android/service/jni').srcnode())
    returnValue += env.Install(serviceDistDir, Dir('android/service/src').srcnode())
    returnValue += env.Install(serviceDistDir, Dir('android/service/res').srcnode())

Return ('returnValue')
