# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# The return value is the collection of files installed in the build destination.
returnValue = []

if env['OS'] != 'win8':
    # Basic Sample programs
    returnValue += env.SConscript('basic/SConscript')

    # Simple Sample programs
    returnValue += env.SConscript('simple/SConscript')

    # Security Sample programs
    returnValue += env.SConscript('secure/SConscript')

    # Chat Sample program
    returnValue += env.SConscript('chat/SConscript')

    # File transfer Sample program
    returnValue += env.SConscript('FileTransfer/SConscript')

# Install readme
if env['OS_CONF'] == 'windows':
    returnValue += env.InstallAs('$DISTDIR/samples/README.txt', 'README.windows.txt')
elif env['OS_CONF'] == 'android':
    returnValue += env.InstallAs('$DISTDIR/samples/README.txt', 'README.android.txt')
elif env['OS_CONF'] == 'linux':
    returnValue += env.InstallAs('$DISTDIR/samples/README.txt', 'README.linux.txt')

Return ('returnValue')
