/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_jni_ScanResultMessage */

#ifndef _Included_org_alljoyn_jni_ScanResultMessage
#define _Included_org_alljoyn_jni_ScanResultMessage
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
