/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_jni_AllJoynAndroidExt */

#ifndef _Included_org_alljoyn_jni_AllJoynAndroidExt
#define _Included_org_alljoyn_jni_AllJoynAndroidExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alljoyn_jni_AllJoynAndroidExt
 * Method:    jniOnCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_alljoyn_jni_AllJoynAndroidExt_jniOnCreate
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_jni_AllJoynAndroidExt
 * Method:    jniOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_jni_AllJoynAndroidExt_jniOnDestroy
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
