# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
clientDistDir = '$CPP_DISTDIR/samples/basic'

# Sample Programs
progs = [
    env.Program('basic_service',  ['basic_service.cc']),
    env.Program('basic_client',   ['basic_client.cc']),
    env.Program('signal_service', ['signal_service.cc']),
    env.Program('nameChange_client', ['nameChange_client.cc']),
    env.Program('signalConsumer_client', ['signalConsumer_client.cc']),
    ]

# The return value is the collection of files installed in the build destination.
returnValue = []

if 'linux' == env['OS'] or 'darwin' == env['OS']:
    returnValue += env.Install('$CPP_DISTDIR/bin/samples', progs )
    returnValue += env.Install(clientDistDir, env.Glob('*.cc'))
    returnValue += env.Install(clientDistDir, 'Makefile')
    returnValue += env.Install(clientDistDir, 'README.txt')
elif env['OS_GROUP'] == 'windows':
    returnValue += env.Install('$CPP_DISTDIR/bin/samples', progs )
    returnValue += env.Install(clientDistDir, env.Glob('*.cc'))
    returnValue += env.InstallAs(clientDistDir + '/README.txt', 'README.windows.txt')
    #install Visual Studio solution files
    returnValue += env.Install(clientDistDir+'/VC2008Win7', 'VC2008Win7/MSVC2008-Win7.sln')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/basic_client', 'VC2008Win7/basic_client/basic_client.vcproj')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/basic_service', 'VC2008Win7/basic_service/basic_service.vcproj')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/nameChange_client', 'VC2008Win7/nameChange_client/nameChange_client.vcproj')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/signal_service', 'VC2008Win7/signal_service/signal_service.vcproj')
    returnValue += env.Install(clientDistDir+'/VC2008Win7/signalConsumer_client', 'VC2008Win7/signalConsumer_client/signalConsumer_client.vcproj')

Return ('returnValue')
