# Copyright 2011-2012, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Install source
if env['OS'] == 'android':
    distDir = '$DISTDIR/alljoyn_android/alljoyn'
    env.Install(distDir, env.Glob('alljoyn/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('alljoyn/.classpath'))
    env.Install(distDir, env.Glob('alljoyn/.project'))
    env.Install(distDir, Dir('alljoyn/.settings').srcnode())
    env.Install(distDir, env.Glob('alljoyn/default.properties'))
    env.Install(distDir, Dir('alljoyn/jni').srcnode())
    env.Install(distDir, Dir('alljoyn/src').srcnode())
    env.Install(distDir, Dir('alljoyn/res').srcnode())

    distDir = '$DISTDIR/alljoyn_android/bundle_test/BundledClient'
    env.Install(distDir, env.Glob('bundle_test/BundledClient/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('bundle_test/BundledClient/.classpath'))
    env.Install(distDir, env.Glob('bundle_test/BundledClient/.project'))
    env.Install(distDir, env.Glob('bundle_test/BundledClient/default.properties'))
    env.Install(distDir, Dir('bundle_test/BundledClient/src').srcnode())
    env.Install(distDir, Dir('bundle_test/BundledClient/res').srcnode())

    distDir = '$DISTDIR/alljoyn_android/bundle_test/BundledService'
    env.Install(distDir, env.Glob('bundle_test/BundledService/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('bundle_test/BundledService/.classpath'))
    env.Install(distDir, env.Glob('bundle_test/BundledService/.project'))
    env.Install(distDir, env.Glob('bundle_test/BundledService/default.properties'))
    env.Install(distDir, Dir('bundle_test/BundledService/src').srcnode())
    env.Install(distDir, Dir('bundle_test/BundledService/res').srcnode())
    
    distDir = '$DISTDIR/alljoyn_android/alljoyn_android_ext'
    env.Install(distDir, env.Glob('alljoyn_android_ext/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('alljoyn_android_ext/.classpath'))
    env.Install(distDir, env.Glob('alljoyn_android_ext/.project'))
    env.Install(distDir, env.Glob('alljoyn_android_ext/default.properties'))
    env.Install(distDir, Dir('alljoyn_android_ext/jni').srcnode())
    env.Install(distDir, Dir('alljoyn_android_ext/src').srcnode())
    env.Install(distDir, Dir('alljoyn_android_ext/res').srcnode())
    
    distDir = '$DISTDIR/alljoyn_android/alljoyn_android_p2pservice'
    env.Install(distDir, env.Glob('alljoyn_android_p2pservice/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('alljoyn_android_p2pservice/.classpath'))
    env.Install(distDir, env.Glob('alljoyn_android_p2pservice/.project'))
    env.Install(distDir, env.Glob('alljoyn_android_p2pservice/default.properties'))
    env.Install(distDir, Dir('alljoyn_android_p2pservice/jni').srcnode())
    env.Install(distDir, Dir('alljoyn_android_p2pservice/src').srcnode())
    env.Install(distDir, Dir('alljoyn_android_p2pservice/res').srcnode())
    
    distDir = '$DISTDIR/alljoyn_android/ice_client_login_service'
    env.Install(distDir, env.Glob('ice_client_login_service/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('ice_client_login_service/.classpath'))
    env.Install(distDir, env.Glob('ice_client_login_service/.project'))
    env.Install(distDir, env.Glob('ice_client_login_service/default.properties'))
    env.Install(distDir, Dir('ice_client_login_service/src').srcnode())
    env.Install(distDir, Dir('ice_client_login_service/res').srcnode())
