# Copyright 2012, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
from os.path import basename

# Clone env so we don't pollute the shared environment
locenv = env.Clone()

# We want to generate documentation for the winrt binding
locenv.Append(CXXFLAGS='/doc');

# Platform specific sources
srcs = [ f for f in locenv.Glob('binding/src/*.cc') ]

objs = locenv.Object(srcs);

# Header file includes
locenv.Prepend(CPPPATH = 'binding/inc')

# Add support for multiple build targets in the same workset
locenv.VariantDir('$OBJDIR', '.', duplicate = 0)

Return('objs')
